/* Generated by Yosys 0.51 (git sha1 c4b5190229616f7ebf8197f43990b4429de3e420, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module bypass(A0, Y, B0, A1, B1, A2, B2, A3, B3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input A0;
  wire A0;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B0;
  wire B0;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input B3;
  wire B3;
  output Y;
  wire Y;
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(_11_),
    .B(_07_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _20_ (
    .A(_10_),
    .B(_06_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(_13_),
    .B(_09_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _22_ (
    .A(_12_),
    .B(_08_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor4_1 _23_ (
    .A(_15_),
    .B(_16_),
    .C(_17_),
    .D(_18_),
    .Y(_14_)
  );
  assign _10_ = B0;
  assign _06_ = A0;
  assign _11_ = B1;
  assign _07_ = A1;
  assign _12_ = B2;
  assign _08_ = A2;
  assign _13_ = B3;
  assign _09_ = A3;
  assign Y = _14_;
endmodule

module cba(S, Cout, Cin, A, B, clk);
  input [15:0] A;
  wire [15:0] A;
  wire A0;
  wire A1;
  wire A10;
  wire A11;
  wire A12;
  wire A13;
  wire A14;
  wire A15;
  wire A2;
  wire A3;
  wire A4;
  wire A5;
  wire A6;
  wire A7;
  wire A8;
  wire A9;
  wire [15:0] Aq;
  input [15:0] B;
  wire [15:0] B;
  wire B0;
  wire B1;
  wire B10;
  wire B11;
  wire B12;
  wire B13;
  wire B14;
  wire B15;
  wire B2;
  wire B3;
  wire B4;
  wire B5;
  wire B6;
  wire B7;
  wire B8;
  wire B9;
  wire [15:0] Bq;
  wire CO;
  input Cin;
  wire Cin;
  wire Cinq;
  output Cout;
  wire Cout;
  output [15:0] S;
  wire [15:0] S;
  wire S0;
  wire S1;
  wire S10;
  wire S11;
  wire S12;
  wire S13;
  wire S14;
  wire S15;
  wire S2;
  wire S3;
  wire S4;
  wire S5;
  wire S6;
  wire S7;
  wire S8;
  wire S9;
  wire [15:0] SO;
  input clk;
  wire clk;
  wire net1;
  wire net10;
  wire net11;
  wire net12;
  wire net13;
  wire net14;
  wire net15;
  wire net16;
  wire net17;
  wire net18;
  wire net19;
  wire net2;
  wire net20;
  wire net21;
  wire net22;
  wire net23;
  wire net3;
  wire net4;
  wire net5;
  wire net6;
  wire net7;
  wire net8;
  wire net9;
  sky130_fd_sc_hd__dfxtp_1 _00_ (
    .CLK(clk),
    .D(S0),
    .Q(S[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _01_ (
    .CLK(clk),
    .D(S1),
    .Q(S[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _02_ (
    .CLK(clk),
    .D(S2),
    .Q(S[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _03_ (
    .CLK(clk),
    .D(S3),
    .Q(S[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _04_ (
    .CLK(clk),
    .D(S4),
    .Q(S[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _05_ (
    .CLK(clk),
    .D(S5),
    .Q(S[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _06_ (
    .CLK(clk),
    .D(S6),
    .Q(S[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _07_ (
    .CLK(clk),
    .D(S7),
    .Q(S[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _08_ (
    .CLK(clk),
    .D(S8),
    .Q(S[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _09_ (
    .CLK(clk),
    .D(S9),
    .Q(S[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _10_ (
    .CLK(clk),
    .D(S10),
    .Q(S[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _11_ (
    .CLK(clk),
    .D(S11),
    .Q(S[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _12_ (
    .CLK(clk),
    .D(S12),
    .Q(S[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _13_ (
    .CLK(clk),
    .D(S13),
    .Q(S[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _14_ (
    .CLK(clk),
    .D(S14),
    .Q(S[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _15_ (
    .CLK(clk),
    .D(S15),
    .Q(S[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(CO),
    .Q(Cout)
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(A[0]),
    .Q(Aq[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(A[1]),
    .Q(Aq[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(A[2]),
    .Q(Aq[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(A[3]),
    .Q(Aq[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(A[4]),
    .Q(Aq[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(clk),
    .D(A[5]),
    .Q(Aq[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _23_ (
    .CLK(clk),
    .D(A[6]),
    .Q(Aq[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _24_ (
    .CLK(clk),
    .D(A[7]),
    .Q(Aq[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _25_ (
    .CLK(clk),
    .D(A[8]),
    .Q(Aq[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _26_ (
    .CLK(clk),
    .D(A[9]),
    .Q(Aq[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _27_ (
    .CLK(clk),
    .D(A[10]),
    .Q(Aq[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _28_ (
    .CLK(clk),
    .D(A[11]),
    .Q(Aq[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _29_ (
    .CLK(clk),
    .D(A[12]),
    .Q(Aq[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _30_ (
    .CLK(clk),
    .D(A[13]),
    .Q(Aq[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _31_ (
    .CLK(clk),
    .D(A[14]),
    .Q(Aq[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(clk),
    .D(A[15]),
    .Q(Aq[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(clk),
    .D(B[0]),
    .Q(Bq[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(clk),
    .D(B[1]),
    .Q(Bq[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _35_ (
    .CLK(clk),
    .D(B[2]),
    .Q(Bq[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _36_ (
    .CLK(clk),
    .D(B[3]),
    .Q(Bq[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _37_ (
    .CLK(clk),
    .D(B[4]),
    .Q(Bq[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _38_ (
    .CLK(clk),
    .D(B[5]),
    .Q(Bq[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _39_ (
    .CLK(clk),
    .D(B[6]),
    .Q(Bq[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _40_ (
    .CLK(clk),
    .D(B[7]),
    .Q(Bq[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _41_ (
    .CLK(clk),
    .D(B[8]),
    .Q(Bq[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(clk),
    .D(B[9]),
    .Q(Bq[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(clk),
    .D(B[10]),
    .Q(Bq[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(clk),
    .D(B[11]),
    .Q(Bq[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(clk),
    .D(B[12]),
    .Q(Bq[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(clk),
    .D(B[13]),
    .Q(Bq[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clk),
    .D(B[14]),
    .Q(Bq[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(clk),
    .D(B[15]),
    .Q(Bq[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(Cin),
    .Q(Cinq)
  );
  fa x1 (
    .A(Bq[0]),
    .B(Aq[0]),
    .Cin(Cinq),
    .Cout(net1),
    .S(S0)
  );
  fa x10 (
    .A(Bq[7]),
    .B(Aq[7]),
    .Cin(net7),
    .Cout(net9),
    .S(S7)
  );
  mux x11 (
    .A0(net9),
    .A1(net10),
    .S(net11),
    .Y(net16)
  );
  bypass x12 (
    .A0(Aq[4]),
    .A1(Aq[5]),
    .A2(Aq[6]),
    .A3(Aq[7]),
    .B0(Bq[4]),
    .B1(Bq[5]),
    .B2(Bq[6]),
    .B3(Bq[7]),
    .Y(net11)
  );
  fa x13 (
    .A(Bq[8]),
    .B(Aq[8]),
    .Cin(net16),
    .Cout(net12),
    .S(S8)
  );
  fa x14 (
    .A(Bq[9]),
    .B(Aq[9]),
    .Cin(net12),
    .Cout(net14),
    .S(S9)
  );
  fa x15 (
    .A(Bq[10]),
    .B(Aq[10]),
    .Cin(net14),
    .Cout(net13),
    .S(S10)
  );
  fa x16 (
    .A(Bq[11]),
    .B(Aq[11]),
    .Cin(net13),
    .Cout(net15),
    .S(S11)
  );
  mux x17 (
    .A0(net15),
    .A1(net16),
    .S(net17),
    .Y(net22)
  );
  bypass x18 (
    .A0(Aq[8]),
    .A1(Aq[9]),
    .A2(Aq[10]),
    .A3(Aq[11]),
    .B0(Bq[8]),
    .B1(Bq[9]),
    .B2(Bq[10]),
    .B3(Bq[11]),
    .Y(net17)
  );
  fa x19 (
    .A(Bq[12]),
    .B(Aq[12]),
    .Cin(net22),
    .Cout(net18),
    .S(S12)
  );
  fa x2 (
    .A(Bq[1]),
    .B(Aq[1]),
    .Cin(net1),
    .Cout(net3),
    .S(S1)
  );
  fa x20 (
    .A(Bq[13]),
    .B(Aq[13]),
    .Cin(net18),
    .Cout(net20),
    .S(S13)
  );
  fa x21 (
    .A(Bq[14]),
    .B(Aq[14]),
    .Cin(net20),
    .Cout(net19),
    .S(S14)
  );
  fa x22 (
    .A(Bq[15]),
    .B(Aq[15]),
    .Cin(net19),
    .Cout(net21),
    .S(S15)
  );
  mux x23 (
    .A0(net21),
    .A1(net22),
    .S(net23),
    .Y(CO)
  );
  bypass x24 (
    .A0(Aq[12]),
    .A1(Aq[13]),
    .A2(Aq[14]),
    .A3(Aq[15]),
    .B0(Bq[12]),
    .B1(Bq[13]),
    .B2(Bq[14]),
    .B3(Bq[15]),
    .Y(net23)
  );
  fa x3 (
    .A(Bq[2]),
    .B(Aq[2]),
    .Cin(net3),
    .Cout(net2),
    .S(S2)
  );
  fa x4 (
    .A(Bq[3]),
    .B(Aq[3]),
    .Cin(net2),
    .Cout(net4),
    .S(S3)
  );
  mux x5 (
    .A0(net4),
    .A1(Cinq),
    .S(net5),
    .Y(net10)
  );
  bypass x6 (
    .A0(Aq[0]),
    .A1(Aq[1]),
    .A2(Aq[2]),
    .A3(Aq[3]),
    .B0(Bq[0]),
    .B1(Bq[1]),
    .B2(Bq[2]),
    .B3(Bq[3]),
    .Y(net5)
  );
  fa x7 (
    .A(Bq[4]),
    .B(Aq[4]),
    .Cin(net10),
    .Cout(net6),
    .S(S4)
  );
  fa x8 (
    .A(Bq[5]),
    .B(Aq[5]),
    .Cin(net6),
    .Cout(net8),
    .S(S5)
  );
  fa x9 (
    .A(Bq[6]),
    .B(Aq[6]),
    .Cin(net8),
    .Cout(net7),
    .S(S6)
  );
  assign A0 = Aq[0];
  assign A1 = Aq[1];
  assign A10 = Aq[10];
  assign A11 = Aq[11];
  assign A12 = Aq[12];
  assign A13 = Aq[13];
  assign A14 = Aq[14];
  assign A15 = Aq[15];
  assign A2 = Aq[2];
  assign A3 = Aq[3];
  assign A4 = Aq[4];
  assign A5 = Aq[5];
  assign A6 = Aq[6];
  assign A7 = Aq[7];
  assign A8 = Aq[8];
  assign A9 = Aq[9];
  assign B0 = Bq[0];
  assign B1 = Bq[1];
  assign B10 = Bq[10];
  assign B11 = Bq[11];
  assign B12 = Bq[12];
  assign B13 = Bq[13];
  assign B14 = Bq[14];
  assign B15 = Bq[15];
  assign B2 = Bq[2];
  assign B3 = Bq[3];
  assign B4 = Bq[4];
  assign B5 = Bq[5];
  assign B6 = Bq[6];
  assign B7 = Bq[7];
  assign B8 = Bq[8];
  assign B9 = Bq[9];
  assign SO = { S15, S14, S13, S12, S11, S10, S9, S8, S7, S6, S5, S4, S3, S2, S1, S0 };
endmodule

module fa(S, A, B, Cout, Cin);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input A;
  wire A;
  input B;
  wire B;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output S;
  wire S;
  sky130_fd_sc_hd__maj3_1 _10_ (
    .A(_06_),
    .B(_05_),
    .C(_07_),
    .X(_08_)
  );
  sky130_fd_sc_hd__xor3_1 _11_ (
    .A(_06_),
    .B(_05_),
    .C(_07_),
    .X(_09_)
  );
  assign _06_ = B;
  assign _05_ = A;
  assign _07_ = Cin;
  assign S = _09_;
  assign Cout = _08_;
endmodule

module mux(A0, Y, A1, S);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
  output Y;
  wire Y;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_0_),
    .A1(_1_),
    .S(_2_),
    .X(_3_)
  );
  assign _0_ = A0;
  assign _1_ = A1;
  assign _2_ = S;
  assign Y = _3_;
endmodule
